### ISSUE TITLE
运行时报错，缺少模块

### ISSUE THREAD

**Issue by 1529960009** [cc004/autopcr#1]
![QQ截图20221108111346](https://user-images.githubusercontent.com/45947734/200466865-c3a27685-566f-4627-aa42-a348c5269e02.png)

**Comment by cc004** [comment]
目前仅写好基本模块和test 暂不支持机器人

**Comment by 1529960009** [comment]
在linus中运行清日常报错。
![QQ截图20221109025753](https://user-images.githubusercontent.com/45947734/200652675-43ec10b8-0ac3-44d0-a2ea-ecfbdf2c7f25.png)
![QQ截图20221109030139](https://user-images.githubusercontent.com/45947734/200652933-09b64886-3ae2-488f-b0b7-05aac7503e27.png)
在Windows中，运行清日常，并没有出现相同的问题。
![QQ截图20221109025929](https://user-images.githubusercontent.com/45947734/200652687-02c57bc9-ce13-41e5-beed-f04ebb62662a.png)
