### ISSUE TITLE
安装依赖后启动报错

### ISSUE THREAD

**Issue by 1529960009** [cc004/autopcr#12]
![QQ截图20230521232158](https://github.com/cc004/autopcr/assets/45947734/7b2b11a5-267d-4a9d-8209-68f655e9f0be)

**Comment by 1529960009** [comment]
![QQ截图20230521232521](https://github.com/cc004/autopcr/assets/45947734/bc420bfa-a567-49bf-8c9a-6b5b0ce8e1d3)
，更换依赖版本，正常启动后，网页报错

**Comment by cc004** [comment]
网页地址为/daily
