### ISSUE TITLE
[Feature Request] 免费十连自动选择抽奖碎片的功能

### ISSUE THREAD

**Issue by cc004** [cc004/autopcr#134]
这是一个悲伤的故事
![M7$YOAGBPDD(BA3B0)R}2%8_tmb](https://github.com/user-attachments/assets/c7bf0949-899a-4809-9922-14a18d976e81)

**Comment by cca2878** [comment]
难得见cc这么着急…
这就来搞（

**Comment by ipearlsnow** [comment]
你确实是神人 蒙葛特怒斥群臣少了一个你
