### ISSUE TITLE
阅读活动剧情 发生了错误。\n回到标题界面。

### ISSUE THREAD

**Issue by cc004** [cc004/autopcr#14]

**Comment by Lanly109** [comment]
有无发生了错误的请求，看看是阅读了哪篇活动剧情
感觉目前活动剧情没啥限制来着，除非是未来的活动剧情，这个貌似没过滤，可以跟`tower剧情`一样看`start_time`

**Comment by cc004** [comment]
都读过了就会这样

**Comment by cc004** [comment]
`"story_id": 5050001`

**Comment by Lanly109** [comment]
> 看了一下 似乎是因为我以前有一个活动没参加，看的是以前的活动的剧情：
> `INSERT INTO "main"."event_story_data" ("story_group_id", "story_type", "value", "title", "thumbnail_id", "disp_order", "start_time", "end_time") VALUES (5050, 5, 10050, '尖叫！连连！万圣鬼怪狂欢节', 0, 1, '2022/09/23 15:00:00', '2099/12/31 23:59:59');`

我有个号去年下半年的活动也没参加，在客户端里的活动剧情里确实没看到，但我上个月我测的时候它可以正常阅读的（难道最近服务端改了）

我记得`loadindex`里有个`unlock_story_ids`，可能是这里有能阅读的剧情（参加过活动的）

不过我刚刚看了下数据库里已经有下次活动的剧情（`5068001`）了（但怎么没报错

**Comment by Lanly109** [comment]
说的对，我发现就只有
https://github.com/cc004/autopcr/blob/001e294ee95c609c31259289541d746802d92bf0/autopcr/module/modules.py#L379
这里考虑了。

当初`阅读活动剧情`是当期的活动，所以就根据`top`里的`story`一路读过去，后来改成读往期的忘记加了。
