### ISSUE TITLE
作为hoshinobot的插件出现一直在清日常列队

### ISSUE THREAD

**Issue by qwe3107231** [cc004/autopcr#25]
![QQ图片20230605180757](https://github.com/cc004/autopcr/assets/73685785/89d2fb06-8403-4613-aad9-b88fac828ccb)
![QQ图片20230605180751](https://github.com/cc004/autopcr/assets/73685785/27c2eb2f-a403-4345-92a7-711e8f6d597a)
后台无报错，主动触发和定时触发都会出现这个问题。基本是需要重启hoshinobot后才能正常

**Comment by cc004** [comment]
看一下你这里面用的是auto还是manual
https://github.com/cc004/autopcr/blob/c36c9bc703b940bd69a2d255e00b067c431caab5/autopcr/bsdk/bsdkclient.py#L18

**Comment by Lanly109** [comment]
有正常清日常给出反馈结果吗？
在bot启动是是否有报错信息？

**Comment by qwe3107231** [comment]
![QQ截图20230605182127](https://github.com/cc004/autopcr/assets/73685785/04b576aa-0836-419f-9bdd-215f6219509c)
![QQ图片20230605182151](https://github.com/cc004/autopcr/assets/73685785/4a18e2a2-653f-4581-89f0-a79b8dd4c268)
重启hoshinobot后能正常清日常

**Comment by qwe3107231** [comment]
![QQ截图20230605182624](https://github.com/cc004/autopcr/assets/73685785/fe081f0d-db66-49da-b14d-d6002c0f0b1c)
我定时任务设置到18:00，发现又卡在列队后18:04分重启的。只有一个反并发插件的报错。autopcr插件无报错

**Comment by Lanly109** [comment]
有无复现的方式。感觉不太晓得原因

**Comment by qwe3107231** [comment]
手动自动都会出现，一般今天重启hoshinobot后 定时任务都能正常执行（也就三个人用分别是18:00,19:00,22:00,）等到第二天就会重现这个问题（家庭宽带，半夜会重新分配IP，刚才我测试了手动重新获取了IP也没有出现这个问题，连续手动触发也没有复现）难道是时间段问题？？

**Comment by qwe3107231** [comment]
![3R9U0 5O XCFN@ _10YCN}V](https://github.com/cc004/autopcr/assets/73685785/c62cf311-d431-4474-8f1c-3536520d2c8a)
感觉出问题都是18：00左右？

**Comment by Lanly109** [comment]
感觉是consuming的线程挂掉了，晚点我加个报错信息反馈，看看是什么问题

**Comment by qwe3107231** [comment]
![QQ图片20230605235741](https://github.com/cc004/autopcr/assets/73685785/d4c817d8-486c-4bc5-ab6e-e5c455b43621)
hoshinobot启动时只要出现
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<consumer() done, defined at c:\Users\Administrator\HoshinoBot\hoshino\modules\autopcr\server.py:66> exception=RuntimeError("Task <Task pending name='Task-4' coro=<consumer() running at c:\\Users\\Administrator\\HoshinoBot\\hoshino\\modules\\autopcr\\server.py:72>> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "c:\Users\Administrator\HoshinoBot\hoshino\modules\autopcr\server.py", line 72, in consumer
    task = await queue.get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\queues.py", line 163, in get
    await getter
RuntimeError: Task <Task pending name='Task-4' coro=<consumer() running at c:\Users\Administrator\HoshinoBot\hoshino\modules\autopcr\server.py:72>> got Future <Future pending> attached to a different loop
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<manual_validate() done, defined at c:\Users\Administrator\HoshinoBot\hoshino\modules\autopcr\server.py:87> exception=RuntimeError("Task <Task pending name='Task-5' coro=<manual_validate() running at c:\\Users\\Administrator\\HoshinoBot\\hoshino\\modules\\autopcr\\server.py:90>> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "c:\Users\Administrator\HoshinoBot\hoshino\modules\autopcr\server.py", line 90, in manual_validate
    (challenge, gt, userid) = await validate_queue.get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\queues.py", line 163, in get
    await getter
RuntimeError: Task <Task pending name='Task-5' coro=<manual_validate() running at c:\Users\Administrator\HoshinoBot\hoshino\modules\autopcr\server.py:90>> got Future <Future pending> attached to a different loop
就会出现这个情况。我多次重启hoshinobot大概有50%概率出现。

**Comment by cc004** [comment]
nonebot以前版本bug会导致有时bot的处理和get_event_loop不是同一个event_loop，先看一下你nb的版本吧

**Comment by qwe3107231** [comment]
![QQ截图20230606002735](https://github.com/cc004/autopcr/assets/73685785/78769ace-b396-431e-8f6a-bbaa4ed9a474)
请问要什么版本？

**Comment by qwe3107231** [comment]
emmm萌新表示没看懂，把你发的safeservice.py里面的代码 复制到server.py里面 然后把sv = Service( 改成sv = SafeService( ？

**Comment by qwe3107231** [comment]
![QQ截图20230606004722](https://github.com/cc004/autopcr/assets/73685785/52d876f1-6842-466a-bbca-3f478cc10189)
![QQ截图20230606004803](https://github.com/cc004/autopcr/assets/73685785/21220887-ae43-448f-a6bb-69bd63414652)
不知道对不对？我这样做了之后，还是会出现

**Comment by cc004** [comment]
https://github.com/cc004/autopcr/blob/c36c9bc703b940bd69a2d255e00b067c431caab5/server.py#L114
这里改成
```python
loop = sv.invokeloop
```

**Comment by Lanly109** [comment]
好怪，我的`nonebot`版本是`1.8.0`

**Comment by cc004** [comment]
> 好怪，我的`nonebot`版本是`1.8.0`

仔细看了一下 或许是apscheduler版本？

**Comment by Lanly109** [comment]
> 仔细看了一下 或许是apscheduler版本？

看到了你当时提的[issue](https://github.com/nonebot/nonebot/issues/259)，好像要升到`3.7.0`。（但好像我没装？`pip list`没找到

**Comment by qwe3107231** [comment]
已近按照各位大佬的方法修改，目前还未没出现问题。我先跑几天看看
