### ISSUE TITLE
执行清日常出现报错

### ISSUE THREAD

**Issue by 1529960009** [cc004/autopcr#26]
![image](https://github.com/cc004/autopcr/assets/45947734/0621b605-0dc2-4274-9b26-99fce61e200a)

**Comment by cc004** [comment]
https://github.com/cc004/autopcr/blob/c36c9bc703b940bd69a2d255e00b067c431caab5/autopcr/module/modulebase.py#L116
这里defaultvalue应该加上qq之类的

**Comment by Lanly109** [comment]
是不是单纯了注册没配置呀，但凡配置过的都应该有qq这个key才对，毕竟插件版qq配置至少要有的。
默认生成的确实得加个qq的好点

**Comment by 1529960009** [comment]
![image](https://github.com/cc004/autopcr/assets/45947734/e52add3e-1ae3-424c-b8c6-b8a26a339d56)
config配置中，是存在qq的

**Comment by Lanly109** [comment]
所有的json文件都存在qq？

**Comment by 1529960009** [comment]
> 所有的json文件都存在qq？

有些没有
