### ISSUE TITLE
目前个人使用过程中无法正常运作的功能汇总

### ISSUE THREAD

**Issue by CCA2878** [cc004/autopcr#32]
地下城扫荡 underground_skip
露娜塔回廊扫荡 tower_cloister_sweep
六星碎片本扫荡 six_star
活动H图扫荡 hatsune_h_sweep

#以下的功能是在某次commit之后失效的
地下城扫荡 underground_skip
家园家具升级 room_upper_all
基本信息 user_info

暂时遇到的就这些，给大佬参考
或者等怡宝，他说六月底把之前的开源出来（）

**Comment by cc004** [comment]
能不能详细说一下无法正常运作具体是怎么
因为我现在用的是没问题的
我比较怀疑是因为你用的纯网页端导致没有自动更新数据库导致没有新图数据

**Comment by CCA2878** [comment]
> 能不能详细说一下无法正常运作具体是怎么 因为我现在用的是没问题的 我比较怀疑是因为你用的纯网页端导致没有自动更新数据库导致没有新图数据

确实是纯网页并且并不是很清楚更新数据库相关…稍后我把控制台log贴一下，

**Comment by cc004** [comment]
这个是准备咕咕咕到下周三以后（你可以尝试临时把
https://github.com/cc004/autopcr/blob/de6575173389e16a01b3e4ca2ad7f0f5d9e9e64f/server.py#L130
移入网页端的自动执行来自动更新数据库

**Comment by CCA2878** [comment]
> 这个是准备咕咕咕到下周三以后（你可以尝试临时把
> 
> https://github.com/cc004/autopcr/blob/de6575173389e16a01b3e4ca2ad7f0f5d9e9e64f/server.py#L130
> 
> 
> 移入网页端的自动执行来自动更新数据库

感谢指导。刚刚看了下控制台log，基本以KeyError和ValueError为主，大概更了数据库就能好…尝试ing

**Comment by CCA2878** [comment]
> 这个是准备咕咕咕到下周三以后（你可以尝试临时把
> 
> https://github.com/cc004/autopcr/blob/de6575173389e16a01b3e4ca2ad7f0f5d9e9e64f/server.py#L130
> 
> 
> 移入网页端的自动执行来自动更新数据库

考虑到已经在TODO List，临时简单地把函数拎出来做了个单独的更新脚本，问题解决，非常感谢，期待冲佬发挥（）
