### ISSUE TITLE
地下城，礼物箱，心碎，刷hard，基本信息报错

### ISSUE THREAD

**Issue by 1529960009** [cc004/autopcr#35]
![image](https://github.com/cc004/autopcr/assets/45947734/4def66e3-63a4-4f07-ac29-e7eb54922ee1)
![image](https://github.com/cc004/autopcr/assets/45947734/77ece7f7-f25a-4589-a200-5207c8602671)
![image](https://github.com/cc004/autopcr/assets/45947734/b3fc95a6-aee6-41f9-b9e7-d6526e526a86)

**Comment by Lanly109** [comment]
数据库版本不是最新的，
发送【#强制更新数据库】更新一下数据库

**Comment by 1529960009** [comment]
问题已解决
