### ISSUE TITLE
最新版本运行报错

### ISSUE THREAD

**Issue by 1529960009** [cc004/autopcr#4]
![QQ截图20221124144830](https://user-images.githubusercontent.com/45947734/203713981-d1cd3e67-4d34-48af-a65a-01c94548398c.png)

**Comment by cc004** [comment]
本问题已在[e1bee673e7d080101abc71789245171d3612b6de](https://github.com/cc004/autopcr/commit/e1bee673e7d080101abc71789245171d3612b6de)中解决

**Comment by 1529960009** [comment]
![image](https://user-images.githubusercontent.com/45947734/221772964-929da6c2-7da4-42c1-b31c-02e7516068a9.png)，删除pcrclient.py中的rate和code才能正常运行
