### ISSUE TITLE
插件版网页主动清日常

### ISSUE THREAD

**Issue by cc004** [cc004/autopcr#46]
群内使用指令允许/禁止网页清日常

**Comment by cca2878** [comment]
指令开关很容易实现，网页api那边判断就行。就是怎么把网页和bot执行流程兼容。

**Comment by cc004** [comment]
理论上现在就是兼容的 不会有顶号问题

**Comment by cca2878** [comment]
> 理论上现在就是兼容的 不会有顶号问题

之前的pr改过了？

**Comment by cca2878** [comment]
> unified那个commit改的

那挺好。话说这个整完了还有啥计划不？（以免写着写着发现合不进去了）

**Comment by Lanly109** [comment]
> 那挺好。话说这个整完了还有啥计划不？（以免写着写着发现合不进去了）

要说还是有，但就是咕咕咕。
比如商店购买的优化，主动买体力换成消耗体力数，以及还没被覆盖的5个日常任务之类的

**Comment by cca2878** [comment]
> > 那挺好。话说这个整完了还有啥计划不？（以免写着写着发现合不进去了）
> 
> 要说还是有，但就是咕咕咕。 比如商店购买的优化，主动买体力换成消耗体力数，以及还没被覆盖的5个日常任务之类的

🉑，这段时间就做点小修小补了
另外读剧情为什么没有读公会剧情？

**Comment by Lanly109** [comment]
> 另外读剧情为什么没有读公会剧情？

因为公会剧情有个前提条件是公会成员的亲密度的要求，目前还没做这个判断，因而还没这个功能。

以及公会剧情的优先度没其他两个高，就没先做了。哪天有空了就可以加上
