### ISSUE TITLE
自动过验证码的url显示deprecate

### ISSUE THREAD

**Issue by Lanly109** [cc004/autopcr#5]
`autopcr/bsdk/validator.py`的14行，对网址`http://pcrd.tencentbot.top/validate`进行`post`的结果是`This API has been deprecate,please use /geetest`，参照[pcrjjc2](https://github.com/cc004/pcrjjc2/blob/main/__init__.py#L103)的代码换成`https://pcrd.tencentbot.top/geetest`，`post`返回`405 Method Not Allowe`，`get`返回`404 Not Found`。不知道是不是目标网站的失效了还是其他原因。

另外[pcrjjc2](https://github.com/cc004/pcrjjc2/blob/main/__init__.py#L103)看不太懂诶，按理说返回的`uuid`是验证请求的序号，用来查询结果的，但它就向`https://pcrd.tencentbot.top/geetest`进行`get`了一下获得到的`uuid`，没有附带任何数据（比如[这里](https://github.com/cc004/autopcr/blob/main/autopcr/bsdk/validator.py#L14)的就附带了包含验证码的网址），它如何知道要过哪个验证码获得的validation?

辛苦冲冲dalao看看了qwq

**Comment by cc004** [comment]
@lulu666lulu

**Comment by cc004** [comment]
问过了 自动过码跑路了，可以考虑改成用jjc2的手动过码
https://github.com/cc004/pcrjjc2/issues/113

**Comment by Lanly109** [comment]
好像还是一样的情况……？

用`curl`的
<img width="680" alt="image" src="https://user-images.githubusercontent.com/32431960/230428670-9b52561c-23f1-451f-9fd2-3a1eb6b529a1.png">

用`validator.py`，网址是`https://pcrd.tencentbot.top/geetest`，结果也是
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/32431960/230428799-6396268d-8d7f-40d9-9a75-4be6474a5f4b.png">
