### ISSUE TITLE
不支持中文用户名

### ISSUE THREAD

**Issue by cc004** [cc004/autopcr#58]
虽然很逆天 但是真有人账户名是中文

**Comment by cca2878** [comment]
我记得网页和api都做了正则的啊（）

**Comment by Lanly109** [comment]
> 我记得网页和api都做了正则的啊（）

是账密登录的，不是主页登录的

**Comment by cca2878** [comment]
> > 我记得网页和api都做了正则的啊（）
> 
> 是账密登录的，不是主页登录的

az，你b的神奇操作
