### ISSUE TITLE
关于自动过码的

### ISSUE THREAD

**Issue by Lanly109** [cc004/autopcr#6]
最近突然要验证码了，而且验证码变成点击文字，而不是三维空间点小球的，之前`re_new`的那个自动过码提交请求后查询结果返回了`500`，不知是验证码类型变了后端验证没变还是有其他验证（看群里看到的）

另外冲冲6.2.0的改动好大qwq尤其是将`response`的`update`单独提出来，用`handle`修饰器处理，这从代码上来看能让各类的职责更加鲜明，但把`update`单独提出来，在编写时又得回去看`response`的定义，另一方面在查错（比如某些物品忘记更新）时得两个文件来回切换。（当然主要是补充了很多update，迁移代码代码比较麻烦qwq

**Comment by cc004** [comment]
自动过码在b站换新码之后就挂掉了 所以换成手动了
换成handler是因为requests是自动生成的，会导致写好的update被覆盖掉，所以就提出来了。

**Comment by cc004** [comment]
迁移代码的话 其实用正则替换一下就好了 只要删除字段 更改父类

**Comment by Lanly109** [comment]
> 换成handler是因为requests是自动生成的，会导致写好的update被覆盖掉，所以就提出来了。

有道理，感谢冲冲dalao

**Comment by cc004** [comment]
说起来 如果你有新的handler其实最好pr一下（因为过几天会对标怡宝清日常加很多新功能 可能会出很多conflict

**Comment by Lanly109** [comment]
好哇，期待怡宝的智能刷图
