### ISSUE TITLE
作为hoshino插件运行时，发送指令会报错'Styler' object has no attribute 'to_html

### ISSUE THREAD

**Issue by V1046-R** [cc004/autopcr#89]
[2023-12-11 12:55:38,809 nonebot] INFO: Self: 53498118, Message ******** from ****
****@[群:********]: '#刷图推荐'
[2023-12-11 12:55:38,812 自动清日常] INFO: Message ******** triggered wrapper.
using cache D:\Pcrbot_Test3\HoshinoBot_Test3\hoshino\modules\autopcr\autopcr\..\
./cache/buffer\buffer.json
None requested SourceIniIndexRequest at /source_ini/index?format=json
None requested SourceIniGetMaintenanceStatusRequest at /source_ini/get_maintenan
ce_status?format=json
None requested ToolSdkLoginRequest at /tool/sdk_login
None requested CheckGameStartRequest at /check/game_start
None requested CheckAgreementRequest at /check/check_agreement
None requested LoadIndexRequest at /load/index
房东 requested HomeIndexRequest at /home/index
Traceback (most recent call last):
  File "D:\Pcrbot_Test3\HoshinoBot_Test3\hoshino\modules\autopcr\_task.py", line
 40, in do_task
    img = await draw(resp, alian + '_' + '_'.join(self.do_module_list()), self.c
allback.qid)
  File "D:\Pcrbot_Test3\HoshinoBot_Test3\hoshino\modules\autopcr\_util.py", line
 75, in draw
    imgkit.from_string(df.to_html(index=False, escape=False), file)
**AttributeError: 'Styler' object has no attribute 'to_html'**

----------------------------
运行系统为windows7
wkhtmltoimage已安装
requirements.txt内依赖均已安装。
直接作为网页版运行都没有问题，均正常。
作为hoshino插件运行时，发送指令后返回就会报错**AttributeError: 'Styler' object has no attribute 'to_html'**
另外在http_server文件夹下并未发现名为static的文件夹。

求教，感谢！

**Comment by Lanly109** [comment]
噢`README`忘了更新，是`assets`文件夹。
至于那个报错问题，看看你的`pandas`库的版本？感觉是太旧了

**Comment by V1046-R** [comment]
> 噢`README`忘了更新，是`assets`文件夹。 至于那个报错问题，看看你的`pandas`库的版本？感觉是太旧了

好，去尝试更新一下

**Comment by V1046-R** [comment]
问题得到解决，感谢！
