### ISSUE TITLE
关于商店购买的限制

### ISSUE THREAD

**Issue by Lanly109** [cc004/autopcr#9]
关于角色碎片，虽然客户端做了购买限制（即到达一定数量就不能购买），但服务端并没没有这个检查，实际可以继续购买。
所以我写的部分仅仅是区分了仅购买装备、仅购买角色碎片（普通商店就是经验药水和强化石），还是都购买，因为有这个选项，并且不同商店的内容是不一样的（总的来说有三类，经验药水+强化石，角色碎片和装备，经验药水和装备），重置次数选项就不晓得加在哪里好一点。

**Comment by Lanly109** [comment]
我整理一下代码晚些时候把剩下的部分上传吧

**Comment by cc004** [comment]
重置感觉其实可以另起一个选项然后注入`client.keys`，像被动体力限制一样

**Comment by Lanly109** [comment]
目前想到的也只有这种办法

**Comment by Lanly109** [comment]
oh no，我也刚写好了（）

**Comment by cc004** [comment]
()
